version: '2'

services:
    nginx:
        image: nginx
        volumes:
            - ./nginx/site-enabled:/etc/nginx/conf.d
        ports:
            - "0.0.0.0:80:80"
    api:
        build: ./api
        volumes:
            - ./api/gateway:/var/www/html
        entrypoint: php /var/www/html/bin/console server:run api:8000
    ms1:
        build: ./ms1
        restart: always
        volumes:
            - ./ms1/resolvers:/var/www/html
        entrypoint: php /var/www/html/bin/console server:run ms1:8001
    ms1_db:
        image: sameersbn/postgresql:9.6-2
        restart: always
        ports:
            - "5432:5432"
        environment:
            - DEBUG=false
            - DB_USER=online
            - DB_PASS=online_ms1
            - DB_NAME=ms1
        volumes:
            - ./ms1/database:/var/lib/postgresql
    ms2:
        image: golang:1.8
        volumes:
            - "./ms2:/ms2"
        command: /ms2/start.sh
    ms3:
        image: golang:1.8
        volumes:
            - "./ms3:/ms3"
        command: /ms3/start.sh








